# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    packageType: 'sdk'
    useGlobalJson: true
- script: dotnet publish Sandbox.sln --self-contained -r linux-x64 -o publish
  displayName: 'build and publish'
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'leastprivilege(b4f1893e-53e4-474d-aee5-7c0db5668eee)'
    appType: 'webAppLinux'
    WebAppName: 'is4sandbox'
    packageForLinux: 'publish'
    RuntimeStack: 'DOTNETCORE|3.0'
    StartupCommand: '/home/site/wwwroot/Sandbox'